In functia main am apelat functiile testCreateSave, in care creez un obiect catalog cu nume si path, un obiect document cu id si nume, apoi am folosit functia addTag pentru a ii oferi informatii suplimentare, dupa documentul a fost introdus in lista creata in catalog. Dupa aceasta, am folosit functia statica save din clasa CatalogUtil. Functiile FileOutputStream si ObjectOutputStream de ocupa de serializarea obiectelor intr-un path deja cunoscut, iar functia writeObject scrie in spatiul nou deschis obiectul catalog cu tot ceea ce contine. In cazul in care nu putem lucra cu fisierul, avem exceptia IOException.
In functia testLoadView apelam functia statica load, tot din catalog util, dar de data aceasta deserializam fisierul si apoi citim ceea ce se gaseste in el. Facem un cast la Catalog. Avem exceptii pentru diferite probleme, dar si functia trimite o exceptie personalizata care se prinde in main. In view ar trebui sa putem vedea pe desktop ceea ce am scris.

Problema este ca intra in exceptii, mai exact in save intra in IOException, nu gaseste sau nu reuseste sa scrie in fisier. Si din moment ce acest lucru nu merge, nici celelalte nu merg. Am folosit exceptii in interiorul functiei pentru a sti mai bine unde imi da exceptia, decat sa dau titlul functiei si nu as sti ce exceptie mi-ar da. O alta problema peste care am dat a fost la view cu File, pentru ca nu stiam cum sa aflu pathul acesteia, dar cu o cautare pe docs.oracle am gasit ce faceam gresit. La fel si la path.
